[package]
name = "isdb"
version = "0.0.0"

edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
memchr = "2.5.0"

[dev-dependencies]
assert_matches = "1.5.0"
hex-literal = "0.3.4"
