name: ci

env:
  rust_stable: stable
  rust_min: 1.66.0

  RUSTFLAGS: -Dwarnings

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: sudo ./.gitlab/setup-deps.sh
        if: matrix.os == 'ubuntu-latest'
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --workspace

  minrust:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_min }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo check -p isdb --all-features
        env:
          RUSTFLAGS: "" # remove -Dwarnings

  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        image:
          # 直近2バージョン＋LTS
          - ubuntu:22.04
          - ubuntu:22.10
          - ubuntu:23.04
          - fedora:37
          - fedora:38
        include:
          - os: windows-latest
            image: null
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v3
      - run: ./.gitlab/setup-deps.sh
        if: matrix.os == 'ubuntu-latest'
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo build -p tavoo
